### ISSUE TITLE
can not add breakpoints  

### ISSUE THREAD

**Issue by whp98** [expo/vscode-expo#191]
### Description of the bug
How would you shortly summarise the issue?

i add a breakpoints to app.js , but vscode say can not  add some breakpoints 

![image](https://github.com/expo/vscode-expo/assets/32877126/544cb933-0af6-4eee-bd89-70a112e51e8d)

### To Reproduce
What steps did you perform which led to this issue?

1. i start a expo app and  add a breakpoint

![image](https://github.com/expo/vscode-expo/assets/32877126/160c0835-cbb5-4b72-9e01-40a75fcfaba5)

2. my launch.json 

``` json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "expo",
      "request": "attach",
      "name": "Debug Expo app",
      "projectRoot": "${workspaceFolder}",
      "bundlerPort": "19000",
      "bundlerHost": "127.0.0.1",
      "enableTurboSourcemaps": true
    }

  ]
}
```

3.vscode  Code Doctor  show wrong code path
![image](https://github.com/expo/vscode-expo/assets/32877126/bf3c413a-d346-43f2-967b-21ac51fd3d8a)

![image](https://github.com/expo/vscode-expo/assets/32877126/f4e2c763-96f3-4543-86c3-b357d3d9315c)

4. debugger can attach to the android emulater  but my breakpoint not work 
5.  i can only use the ctrl + j use chrome to debug

#### Expected behavior
i can add breakpoint in vscode and debug the app
#### Actual behavior
not working

### Additional context
Can you further explain the issue? E.g., information about version/environment or screenshots.

**Comment by byCedric** [comment]
Thanks for reporting the issue! Seems like the capitalization in the drive name throws vscode off. I'll make sure to test this a bit more on Windows.

Just out of curiosity, which one is the correct one? Is your `E:` drive capitalized or lower case (`e:`)?

**Comment by whp98** [comment]
WINDOWS system path does not distinguish between uppercase and lowercase

The problem I'm having is that my code path seems to be repeated twice, and the directory doesn't even exist

The part on my screenshot framed in red is correct

**Comment by AxelKlemm** [comment]
Got the same problem. When trying to set a breakpoint it can't find the location. VS Code reports file location as workspacefolder+fullsourcefilepath - the full path of course already containing the workspace root, just like in @whp98 screenshot above.

**Comment by byCedric** [comment]
Thanks for the additional information. It seems that this issue might actually be caused by the sourcemap path generation or the vscode path mixing. I'll try to investigate on a Windows machine on my end.

**Comment by byCedric** [comment]
Likely related to this issue:

- https://github.com/nodejs/node/issues/38459
- https://github.com/nodejs/node/issues/6624

**Comment by byCedric** [comment]
I just published a pre-release with a potential fix included. You can switch to this version through VS Code, [more info here](https://code.visualstudio.com/updates/v1_63#_pre-release-extensions).

Let me know if this fixes the issue for you.

**Comment by AxelKlemm** [comment]
> I just published a pre-release with a potential fix included. You can switch to this version through VS Code, [more info here](https://code.visualstudio.com/updates/v1_63#_pre-release-extensions).
> 
> Please try version `1.2.1` and let me know if this fixes the issue for you.

Just tried with the 1.2.1 pre-release, unfortunately still getting the same errors...

![image](https://github.com/expo/vscode-expo/assets/32672326/ac67ef7f-06c5-40ba-b1c6-f3e4f3cacf68)

When the debugger attaches massive dump of path mismatches for the sourcemaps:
![image](https://github.com/expo/vscode-expo/assets/32672326/017d9454-022b-4314-bb4e-bcd044661640)

And when you try to set a breakpoint:
![image](https://github.com/expo/vscode-expo/assets/32672326/1e628646-a689-4104-a3fc-b4f383eee220)

Hope this helps a little, thanks for your efforts trying to fix this!

**Comment by orefors** [comment]
I'm still having this exact problem with v 1.2.1 on Windows, any progress on a fix?

**Comment by ghardukan** [comment]
> For anyone on Windows trying to work around this. It appears that it is related to project files not being located on the same drive as the VS Code installation. For me it worked to move the project files to the same drive as the VS Code installation.

don't know why this is not mentioned anywhere this is kind of stupid tbh

**Comment by wchbrad** [comment]
same issue,someone help?

**Comment by d3vpunk** [comment]
same here
seems the selected breakpoints in dev tools are not matching with the actual line the debugger is stopping
